### ISSUE TITLE
Clicking the [-] button makes the comment disappear, rather than minimize

### ISSUE THREAD

**Issue by quenz** [KoffeinFlummi/alientube#10]

**Comment by kufii** [comment]
I fixed this in a pull request, but the dev seems to be ignoring it. In the meantime you can use something like stylish to add the following css rule, it'll fix the issue

```css
#alientube .hidden {
	display: inherit;
}
```
